/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.extracraftx.minecraft.generatorfabricmod;

import com.extracraftx.minecraft.generatorfabricmod.prompter.Prompter;

import org.jline.reader.UserInterruptException;

public class GeneratorFabricMod {

    public static void main(String[] args) {
        try{
            Prompter prompter = new Prompter();
            
            String name = prompter.prompt(
                "Please enter your name:",
                (input)-> input.isEmpty() ? "Your name cannot be empty" : null
            );

            String[] greetings = {"Hello ", "Hi "};
            int greeting = prompter.promptList("Please select a greeting:", true, greetings);

            String[] letters = {"a", "b", "c", "d", "e", "f", "g", "h", "i", "j"};
            int letter = prompter.promptList("Please select a letter:", false, letters);

            System.out.println(greetings[greeting] + name + "!");
            System.out.println(letter != -1 ? "You chose the letter '" + letters[letter] + "'." : "You did not choose a letter.");
        }
        catch(UserInterruptException e){}
        catch(Exception e){
            System.err.println("An unknown error occured. The stack trace follows: ");
            e.printStackTrace();
        }
    }
}
