/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.extracraftx.minecraft.generatorfabricmod;

public class GeneratorFabricMod {

    public static void main(String[] args) {
        System.out.println("Hello world");
    }
}
